apiVersion: v1
kind: Service
metadata:
  name: $app_name
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: $app_name
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000